### ISSUE TITLE
wrong version?

### ISSUE THREAD

**Issue by supertassu** [SkriptLang/skript-aliases#1]
shouldn't this be `1.12 or older`?

https://github.com/bensku/skript-aliases/blob/d090475c1b4b466ae9b6360fa5229cc82f07ce04/foodstuffs.sk#L34-L36

**Comment by TheBentoBox** [comment]
It should. I'll be working on some of these aliases later today hopefully so I'll include a fix for that in my first PR when the time comes (that is if bensku doesn't fix it before me).

**Comment by bensku** [comment]
This will be fixed next time I touch the aliases, which will be after next Skript release. Next week, I think.

**Comment by bensku** [comment]
Fixed.
