### ISSUE TITLE
Support block states on 1.12 and lower

### ISSUE THREAD

**Issue by bensku** [SkriptLang/skript-aliases#3]
Basically, look at https://minecraft.gamepedia.com/Block_states and write a lookup table. Spigot 1.13 has nice API for turning block state string to block data object.

**Comment by bensku** [comment]
Also, gotta document block state support.

**Comment by bensku** [comment]
Work in progress... Docs done. Lookup table *very* incomplete.

**Comment by TheBentoBox** [comment]
On the bright side, the lookup table should be something that only needs to be written once without needing maintenance as any other new blocks added at any point obviously won't exist in the old versions and won't need support for block state lookups.

**Comment by Syst3ms** [comment]
I started a repo for data values <-> block states [here](https://github.com/Syst3ms/DataValueLookup). Right now it's only data value -> block state and it's very incomplete, but I'll get there.

**Comment by bensku** [comment]
Was never implemented, and will not be needed because aliases circumvented this issue.
