### ISSUE TITLE
Banner Item Alias

### ISSUE THREAD

**Issue by wizrow** [SkriptLang/skript-aliases#37]
Iv'e recently updated Minecraft and Skript to their latest versions for version 1.13. Iv'e tested that the different colored banner items aren't working as they should. Every time I reloaded skript the specific colored banner item causes a unknown conditional/effect error.

For example,
`set {_item} to dark gray banner item`
causes an error.

**Comment by ShaneBeee** [comment]
thats because in 2.3 a LOT of the aliases have changed
this one specifically is 
`gray banner`
dark gray should work, but for some reason it is not

**Comment by TheBentoBox** [comment]
`dark gray` works too, you just need to remove the `item` from the end of the alias. Standing banners and the item version of banners have the same ID in 1.13 so they're not differentiated in the aliases, there's just `<color> [standing] banner` and `<color> wall banner`.
