### ISSUE TITLE
Wrong plants in 1.12.2

### ISSUE THREAD

**Issue by MeeRach** [SkriptLang/skript-aliases#38]
![unknown](https://user-images.githubusercontent.com/46353742/51400193-d3714a80-1b58-11e9-9d0c-b9cb24eb7633.png)

Works as expected in 1.13.2
Skript 2.3.1

**Comment by bensku** [comment]
Edit: oops wrong repository, nevermind

**Comment by TheBentoBox** [comment]
The aliases look correct to me, [see here](https://github.com/SkriptLang/skript-aliases/blob/master/decoration.sk#L56) for the normal fern and [see these lines](https://github.com/SkriptLang/skript-aliases/blob/master/decoration.sk#L73-L79) for the large fern and other double height plants.

Just to clarify, the way the double height plants work before 1.13 is that the damage value bottom block is what defines what type the plant is, so double ferns are `minecraft:double_plant` (ID 175) with damage value 3 as shown in the aliases. As I recall, the top block is the *exact same* for all of them: it's a `double_plant` ID 175 with a damage value of 8.

**Comment by MeeRach** [comment]
2.3.3 fixes this
