### ISSUE TITLE
Wrong block comparison

### ISSUE THREAD

**Issue by MeeRach** [SkriptLang/skript-aliases#40]
In version 1.12.2, the blocks are not exactly specified. 
using:
```
on rightclick on a dispenser:
if target block is dispenser:
```
doesn't work.
but using:
```
on rightclick on a north facing dispenser:
if target block is north facing dispenser:
```
works.
works with chests...
Skript version: 2.3.5
Works in 1.13.2

**Comment by TheLimeGlass** [comment]
Skript related not aliases https://github.com/SkriptLang/Skript/issues/2396
