### ISSUE TITLE
Something is wrong with nether quartz block

### ISSUE THREAD

**Issue by MorkaZ** [SkriptLang/skript-aliases#45]
When I try to set variable to nether quartz block item, it gives error "Can't understand this expression: set {_item} to nether quartz block".
```set {_item} to nether quartz block, quartz block, block of nether quartz```
It is possible to solve it in half by adding alias by self to script but parsing will still not work (example below)
```set {_item} to "1 of nether quartz block" parsed as item # it will be <none>```

**Comment by TheLimeGlass** [comment]
Since fixed
