### ISSUE TITLE
Migrate to SkriptLang/Skript aliases

### ISSUE THREAD

**Issue by bensku** [SkriptLang/skript-aliases#47]
I propose that we close the issue tracker of this repo, and instead track all aliases issues in SkriptLang/Skript. Most of aliases-related issues are already posted there, so it would make sense to get *everything* there. Requesting comments from @TheBentoBox

Edit: pull requests would still be tracked here, of course

**Comment by TheBentoBox** [comment]
Makes sense to me, I'd also rather have them all tracked in one place in this case and we already have a label on the main repo for alias-related issues.
