### ISSUE TITLE
Sign alias should not include wall and floor signs when not specified

### ISSUE THREAD

**Issue by sovdeeth** [SkriptLang/skript-aliases#94]
Found by @arcsin0.5 on skript chat discord.

When using `oak sign` or `spruce sign` as an item, eg: giving it to player or setting a slot, the alias can resolve to either floor sign or a wall sign, and a wall sign cannot be given as an item. So half the time giving a sign or setting a slot will silently fail, when not specifying `floor`.

The alias should always return a floor sign, like `torch` always returns a floor torch.
```
[floor] torch¦es = minecraft:torch
any torch = floor torch, north facing wall torch, south facing wall torch, east facing wall torch, west facing wall to…
```
`any oak sign` should still include wall signs, but `oak sign` alone should not.

**Comment by Fusezion** [comment]
honestly I think something needs to be done to stop band aiding it. 
Just forcing it to default to `floor (whatever)` when only `(whatever)` is used doesn't solve the underlining issue.

A method for forcing `wall (whatever)` or `hanging (whatever)` to their item format needs to be added not only for those but `any` as well. if I understand enough it means `give player any sign` would end up giving no item meaning we're just covering up the issue.

**Comment by TheLimeGlass** [comment]
https://github.com/SkriptLang/skript-aliases/pull/88 addresses signs. If this is valid, torches would need work.

**Comment by TheLimeGlass** [comment]
Duplicate as in terms of the inventories https://github.com/SkriptLang/Skript/issues/5586
